import "@/style/globals.css"
import ThemeWrapper from "./ThemeWrapper";
import { HeaderProvider } from "@/context/HeaderContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
          <HeaderProvider>
            <ThemeWrapper>
              {children}
            </ThemeWrapper>
          </HeaderProvider>
        </body>
    </html>
  );
}
