import "@/style/globals.css"
import { Nunito } from 'next/font/google'

import ThemeWrapper from "./ThemeWrapper";
import { HeaderProvider } from "@/context/HeaderContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const nunito_init = Nunito({
  subsets: ['latin'] ,
  weight: ["1000" ,"200","300","400","500","600","700","800","900"],
  variable: '--font-nunito'
})


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={nunito_init.variable}>
          <HeaderProvider>
            <ThemeWrapper>
              {children}
            </ThemeWrapper>
          </HeaderProvider>
        </body>
    </html>
  );
}
